juniper_config_l3vpn_routing_instance_interfaceTable:
  rpc: get-configuration
  #filter_xml: routing-instances
  item: //configuration/routing-instances/instance[instance-type='vrf']/interface
  key: name
  view: _juniper_config_l3vpn_routing_instance_interface_view
_juniper_config_l3vpn_routing_instance_interface_view:
  fields:
    interface-name: name
    instance-name: ../name
    rd: ../route-distinguisher/rd-type
    vrf-import: ../vrf-import
    vrf-export: ../vrf-export


juniper_config_igmp_interfaceTable:
  rpc: get-configuration
  #filter_xml: routing-instances
  item: //configuration/protocols/igmp/interface
  key: name
  view: _juniper_config_igmp_interface_view
_juniper_config_igmp_interface_view:
  fields:
    interface-name: name
    ssm-map-policy: ssm-map-policy
    promiscuous-mode: promiscuous-mode

juniper_config_policy_statement_term_community_conditionTable:
  get: policy-options/policy-statement/term/from/community
  #rpc: get-configuration
  #filter_xml: routing-instances
  #item: //policy-options/policy-statement/term
  #key: 
  #   - name
  #   - ../name
  #required_keys:
  # term: name
  view: _juniper_config_policy_statement_term_community_condition_view
_juniper_config_policy_statement_term_community_condition_view:
  fields:
    term_name: ../../name
    policy_name: ../../../name
    #from: from/protocol