---

### ------------------------------------------------------
### show route <destination>
### ------------------------------------------------------

RouteTable:
  rpc: get-route-information
  args_key: 
    - destination
    - hidden
  args:
    extensive: True
    hidden: False
  item: route-table/rt 
  key: rt-destination
  view: _RouteTableView

_RouteTableView:
  groups:
    entry: rt-entry
  fields_entry:
    # fields taken from the group 'entry'
    protocol: protocol-name
    via: nh/via | nh/nh-local-interface
    age: { age/@seconds : int }
    nexthop: nh/to
    as_path: as-path
    community: communities/community
    preference: preference | local-preference
  fields:
    rt_destination: rt-destination
    rt_prefix_length: rt-prefix-length

### ------------------------------------------------------
### show route summary
### ------------------------------------------------------





RouteSummaryTable:
  rpc: get-route-summary-information
  item: route-table
  key: table-name
  view: _RouteSummaryView

_RouteSummaryView:
  fields:
    table_name: table-name
    dests: { destination-count : int }
    total: { total-route-count : int }
    active: { active-route-count : int }
    holddown: { holddown-route-count : int }
    hidden: { hidden-route-count : int }
    protocols: _rspTable 

_rspTable:
  item: protocols
  key: protocol-name
  view: _rspView

_rspView:
  fields:
    protocol_name: protocol-name
    count: { protocol-route-count: int }
    active: { active-route-count : int }


RouteProtocolsSummaryTable:
  rpc: get-route-summary-information
  item: route-table/protocols
  key: protocol-name
  view: _RouteProtocolsSummary_View
_RouteProtocolsSummary_View:
  fields:
    table_name: ../table-name
    table_dests: ../destination-count
    table_total_count: ../total-route-count
    table_active_route_count: ../active-route-count
    table_holddown_route_count: ../holddown-route-count
    table_hidden_route_count: ../hidden-route-count

    protocol_name: protocol-name
    protocol_route_count: protocol-route-count
    protocol_active_route_count: active-route-count



